// Copyright (c) 2026 BowenLabs. Astroid is MIT licensed.
//
// The release workflow every site runs (louise-toolkit ADR 0017, amended).
//
// Releases are trunk-based: a `v<version>` tag on a commit of `main` is the
// release, and a `release/<version>` branch exists only when a released version
// needs a patch and `main` has moved on. Workers Builds deploys on branch
// pushes and can't watch tags, so the tag's workflow moves one branch,
// `deploy/production`, to the tagged commit, and Workers Builds deploys that.
// Nobody commits to the branch; it's a tag carried as a branch, and GitHub never
// holds a Cloudflare credential.
//
// A regenerated file, like the worker trio: `astroid generate` rewrites it and
// `astroid doctor` fails when it drifts, so a hand edit can't quietly change
// which commits reach production.

/** The branch Workers Builds deploys to production from. */
export const ASTROID_DEPLOY_BRANCH = "deploy/production";

/** Where the workflow lives, relative to the repository root. */
export const ASTROID_RELEASE_WORKFLOW_PATH = ".github/workflows/release.yml";

/** The release workflow's contents. Pure, and the same for every site. */
export function generateAstroidReleaseWorkflow(): string {
  return `# Generated by astroid. Don't edit: \`astroid generate\` rewrites this file and
# \`astroid doctor\` fails when it drifts.
#
# A release is a tag, v<major>.<minor>.<patch>, on a commit of main, or of a
# release/<version> branch when a released version needs a patch. This moves
# ${ASTROID_DEPLOY_BRANCH} to the tagged commit, and Workers Builds deploys it to
# production. Nobody commits to ${ASTROID_DEPLOY_BRANCH}; a repository ruleset lets
# only this workflow update it. To roll back, tag the earlier commit with the
# next patch version.
name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

# One release at a time, in the order the tags arrived.
concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Check the tag
        run: |
          tag="$GITHUB_REF_NAME"
          if ! [[ "$tag" =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$ ]]; then
            echo "::error::A release tag is v<major>.<minor>.<patch>, such as v1.4.0. Got $tag."
            exit 1
          fi
          sha="$(git rev-list -n 1 "$tag")"
          if git merge-base --is-ancestor "$sha" origin/main; then
            echo "$tag is on main."
          elif git branch -r --contains "$sha" | grep -q "origin/release/"; then
            echo "$tag is on a release branch."
          else
            echo "::error::$tag isn't on main or a release/ branch, so it can't be released."
            exit 1
          fi
          echo "SHA=$sha" >> "$GITHUB_ENV"

      - name: Move ${ASTROID_DEPLOY_BRANCH} to the tag
        run: git push --force origin "$SHA:refs/heads/${ASTROID_DEPLOY_BRANCH}"

      - name: Create the GitHub release
        env:
          GH_TOKEN: \${{ github.token }}
        run: gh release create "$GITHUB_REF_NAME" --verify-tag --generate-notes
`;
}
