// Copyright (c) 2026 BowenLabs. Astroid is MIT licensed.
//
// The release workflow every site runs (louise-toolkit ADR 0017, amended).
//
// Releases are trunk-based: a `v<version>` tag on a commit of `main` is the
// release, and a `release/<version>` branch exists only when a released version
// needs a patch and `main` has moved on. Workers Builds deploys on branch
// pushes and can't watch tags, so the tag's workflow moves one branch,
// `deploy/production`, to the tagged commit, and Workers Builds deploys that.
// Nobody commits to the branch; it's a tag carried as a branch, and GitHub never
// holds a Cloudflare credential.
//
// The push uses a GitHub App's token, not the workflow's own `GITHUB_TOKEN`. A
// repository ruleset keeps everyone else off `deploy/production`, and GitHub
// rejects the GitHub Actions app as a ruleset bypass actor, so a ruleset that
// guards the branch blocks `GITHUB_TOKEN` too. A GitHub App can be the bypass
// actor. The setup is in the docs site's Releases guide.
//
// A regenerated file, like the worker trio: `astroid generate` rewrites it and
// `astroid doctor` fails when it drifts, so a hand edit can't quietly change
// which commits reach production.

/** The branch Workers Builds deploys to production from. */
export const ASTROID_DEPLOY_BRANCH = "deploy/production";

/** Where the workflow lives, relative to the repository root. */
export const ASTROID_RELEASE_WORKFLOW_PATH = ".github/workflows/release.yml";

/** The Actions variable that holds the release app's App ID. */
export const ASTROID_RELEASE_APP_ID_VAR = "RELEASE_APP_ID";

/** The Actions secret that holds the release app's private key. */
export const ASTROID_RELEASE_APP_KEY_SECRET = "RELEASE_APP_PRIVATE_KEY";

/** Where the one-time release setup is written down. */
export const ASTROID_RELEASE_SETUP_URL = "https://docs.astroidjs.org/guide/releases/";

/** The release workflow's contents. Pure, and the same for every site. */
export function generateAstroidReleaseWorkflow(): string {
  const appId = ASTROID_RELEASE_APP_ID_VAR;
  const appKey = ASTROID_RELEASE_APP_KEY_SECRET;
  return `# Generated by astroid. Don't edit: \`astroid generate\` rewrites this file and
# \`astroid doctor\` fails when it drifts.
#
# A release is a tag, v<major>.<minor>.<patch>, on a commit of main, or of a
# release/<version> branch when a released version needs a patch. This moves
# ${ASTROID_DEPLOY_BRANCH} to the tagged commit, and Workers Builds deploys it to
# production. Nobody commits to ${ASTROID_DEPLOY_BRANCH}; a repository ruleset lets
# only the release GitHub App update it. To roll back, tag the earlier commit
# with the next patch version.
#
# The push uses the release app's token, from the ${appId} variable and
# the ${appKey} secret. The workflow's own GITHUB_TOKEN can't push:
# GitHub rejects the GitHub Actions app as a ruleset bypass actor, so the
# ruleset blocks it too. One-time setup, the app and the ruleset:
# ${ASTROID_RELEASE_SETUP_URL}
name: Release

on:
  push:
    tags: ["v*"]

permissions:
  contents: write

# One release at a time, in the order the tags arrived.
concurrency:
  group: release
  cancel-in-progress: false

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check the release app
        env:
          APP_ID: \${{ vars.${appId} }}
          APP_KEY: \${{ secrets.${appKey} }}
        run: |
          if [ -z "$APP_ID" ] || [ -z "$APP_KEY" ]; then
            echo "::error::Releasing needs the ${appId} variable and the ${appKey} secret, from the GitHub App that the ${ASTROID_DEPLOY_BRANCH} ruleset lets through. Set them up as ${ASTROID_RELEASE_SETUP_URL} describes."
            exit 1
          fi

      - name: Mint the release app's token
        id: app-token
        uses: actions/create-github-app-token@v2
        with:
          app-id: \${{ vars.${appId} }}
          private-key: \${{ secrets.${appKey} }}

      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # The push below uses the credentials checkout leaves in place.
          token: \${{ steps.app-token.outputs.token }}

      - name: Check the tag
        run: |
          tag="$GITHUB_REF_NAME"
          if ! [[ "$tag" =~ ^v[0-9]+\\.[0-9]+\\.[0-9]+$ ]]; then
            echo "::error::A release tag is v<major>.<minor>.<patch>, such as v1.4.0. Got $tag."
            exit 1
          fi
          sha="$(git rev-list -n 1 "$tag")"
          if git merge-base --is-ancestor "$sha" origin/main; then
            echo "$tag is on main."
          elif git branch -r --contains "$sha" | grep -q "origin/release/"; then
            echo "$tag is on a release branch."
          else
            echo "::error::$tag isn't on main or a release/ branch, so it can't be released."
            exit 1
          fi
          echo "SHA=$sha" >> "$GITHUB_ENV"

      - name: Move ${ASTROID_DEPLOY_BRANCH} to the tag
        run: git push --force origin "$SHA:refs/heads/${ASTROID_DEPLOY_BRANCH}"

      - name: Create the GitHub release
        env:
          GH_TOKEN: \${{ github.token }}
        run: gh release create "$GITHUB_REF_NAME" --verify-tag --generate-notes
`;
}
